### ISSUE TITLE
Startup fails

### ISSUE THREAD

**Issue by robertdebock** [robertdebock/ansible-role-irslackd#1]
**Describe the bug**
After applying this role, the service fails.

**To Reproduce**
1. Run this role.
2. See error

**Expected behavior**
No errors.

**Error**
`systemctl status`:
```
● irslackd.service                        loaded failed failed    A self-hosted IRC gateway to Slack
```

`systemctl status irslackd`:
```
● irslackd.service - A self-hosted IRC gateway to Slack
   Loaded: loaded (/etc/systemd/system/irslackd.service; enabled; vendor preset: disabled)
   Active: failed (Result: exit-code) since Wed 2018-10-24 11:46:28 EDT; 1min 59s ago
 Main PID: 15502 (code=exited, status=1/FAILURE)

Oct 24 11:46:28 robertdebock irslackd[15502]: at Module.load (module.js:494:32)
Oct 24 11:46:28 robertdebock irslackd[15502]: at tryModuleLoad (module.js:453:12)
Oct 24 11:46:28 robertdebock irslackd[15502]: at Function.Module._load (module.js:445:3)
Oct 24 11:46:28 robertdebock irslackd[15502]: at Module.require (module.js:504:17)
Oct 24 11:46:28 robertdebock irslackd[15502]: at require (internal/module.js:20:19)
Oct 24 11:46:28 robertdebock irslackd[15502]: at Object.<anonymous> (/opt/irslackd/bin/irslackd.js:6:18)
Oct 24 11:46:28 robertdebock systemd[1]: irslackd.service: main process exited, code=exited, statu...LURE
Oct 24 11:46:28 robertdebock systemd[1]: irslackd.service: control process exited, code=exited status=203
Oct 24 11:46:28 robertdebock systemd[1]: Unit irslackd.service entered failed state.
Oct 24 11:46:28 robertdebock systemd[1]: irslackd.service failed.
Hint: Some lines were ellipsized, use -l to show in full.
```

`cd /opt/irslackd ; /opt/irslackd/irslackd`:
```
/opt/irslackd/lib/irslackd.js:44
  async onIrcConnect(socket) {
        ^^^^^^^^^^^^

SyntaxError: Unexpected identifier
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:549:28)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)
    at Module.require (module.js:504:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/opt/irslackd/bin/irslackd.js:6:18)
```

**Environment**
- Managed node OS: CentOS 7

**Additional context**
I've followed the setup instructions from [upstream](https://github.com/adsr/irslackd) and can reproduce the error, I guess it's not the role, but an issue with irslackd itself.

**Comment by robertdebock** [comment]
Ah, won't work on CentOS6: node is outdate.
